///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * Copyright (c) 2026 STMicroelectronics.
// * All rights reserved.
// *
// * This software is licensed under terms that can be found in the LICENSE file
// * in the root directory of this software component.
// * If no LICENSE file comes with this software, it is provided AS-IS.
// *
// ******************************************************************************
// */
//
//#include <stdint.h>
//
//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
//
//int main(void)
//{
//    /* Loop forever */
//	for(;;);
//}
//bootloader
//#include<stdio.h>
//#include<stdint.h>
//volatile uint32_t *const GPIO_MODER = (volatile uint32_t*)0x40010000;
//volatile uint32_t *const GPIO_IDR   = (volatile uint32_t*)0x40010008;
//#define APP_ADDRESS 0x08004000
//void init_gpio(){
//	*GPIO_MODER &= ~(3U<<(0*2));
//}
//void jump_to_app(){
//	uint32_t *app_sp = (uint32_t*)APP_ADDRESS;
//	uint32_t *app_reset = (uint32_t*)(APP_ADDRESS + 4);
//	__asm volatile ("msr msp,%0"::"r"(*app_sp));
//	((void (*)(void)) *app_reset)();
//}
//void delay_ms(uint32_t ms){
//	for(uint32_t i =0;i<16000*ms;i++){
//		__asm volatile ("nop");
//	}
//}
//int main(){
//	init_gpio();
//	if(*GPIO_IDR & (1U<<0)){
//		printf("Update mode: Waiting for firmware...\n");
//		delay_ms(5000);
//	}else{
//		printf("jumping to the application");
//		jump_to_app();
//	}
//	return 0;
//}
//#include <stdint.h>
//
//#define APP_ADDRESS       0x08004000
//
//// STM32F411 correct addresses
//#define RCC_AHB1ENR   (*(volatile uint32_t*)0x40023830)
//#define GPIOA_MODER   (*(volatile uint32_t*)0x40020000)
//#define GPIOA_IDR     (*(volatile uint32_t*)0x40020010)
//// PC13 = onboard LED on BlackPill
//#define GPIOC_MODER   (*(volatile uint32_t*)0x40020800)
//#define GPIOC_ODR     (*(volatile uint32_t*)0x40020814)
//
//void init_gpio() {
//    RCC_AHB1ENR |= (1U << 0);  // GPIOA clock
//    RCC_AHB1ENR |= (1U << 2);  // GPIOC clock
//    GPIOA_MODER &= ~(3U << (0 * 2));  // PA0 = input (button)
//    GPIOC_MODER &= ~(3U << (13 * 2));
//    GPIOC_MODER |=  (1U << (13 * 2)); // PC13 = output (LED)
//}
//
//void led_blink(int n) {
//    for (int i = 0; i < n; i++) {
//        GPIOC_ODR &= ~(1U << 13); // ON (active low)
//        for (volatile int d = 0; d < 200000; d++);
//        GPIOC_ODR |=  (1U << 13); // OFF
//        for (volatile int d = 0; d < 200000; d++);
//    }
//}
//
//void jump_to_app() {
//    uint32_t app_sp    = *(volatile uint32_t*)APP_ADDRESS;
//    uint32_t app_reset = *(volatile uint32_t*)(APP_ADDRESS + 4);
//    __asm volatile ("msr msp, %0" :: "r"(app_sp));
//    ((void (*)(void))app_reset)();
//}
//
//int main() {
//    init_gpio();
//
//    if (GPIOA_IDR & (1U << 0)) {
//        led_blink(3);  // 3 blinks = update mode
//        for (volatile int d = 0; d < 5000000; d++);
//    } else {
//        led_blink(1);  // 1 blink = jumping to app
//        jump_to_app();
//    }
//    return 0;
//}
#include<stdio.h>
#include<stdint.h>
#define APP_ADDRESS 0x08004000
#define RCC_AHB1ENR (*(volatile uint32_t*)0x40023830)
#define GPIOA_MODER (*(volatile uint32_t*)0x40020000)
#define GPIOA_IDR   (*(volatile uint32_t*)0x40020010)
#define GPIOC_MODER (*(volatile uint32_t*)0x40020800)
#define GPIOC_ODR   (*(volatile uint32_t*)0x40020814)
void init_gpio(){
	RCC_AHB1ENR |= (1U<<0);
	RCC_AHB1ENR |= (1U<<2);
	GPIOA_MODER &= ~(3U<<(0*2));
	GPIOC_MODER &= ~(3U<<(13*2));
	GPIOC_MODER |= (1U<<(13*2));
}
void led_blink(int n){
	for(int i=0;i<n;i++){
		GPIOC_ODR &= ~(1U<<13);
		for(volatile int d=0;d<200000;d++);
		GPIOC_ODR |= (1U<<13);
		for (volatile int d = 0; d < 200000; d++);
	}
}
void jump_to_app(){
	uint32_t app_sp = *(volatile uint32_t*)APP_ADDRESS;
	uint32_t app_reset = *(volatile uint32_t*)(APP_ADDRESS +4);
	__asm volatile("msr msp , %0"::"r"(app_sp));
	((void (*)(void))app_reset)();
}
int main(){
	init_gpio();
		if(GPIOA_IDR & (1U<<0)){
			led_blink(3);
			for(volatile int d = 0;d<500000;d++);
		}else{
			led_blink(1);
			jump_to_app();
		}
	return 0;
}

























